ext {
	application = [
		name           : 'NettyServer',
		manifestVersion: '1.0',
		mainClass      : '',
	]

	versions = [
		javaVersion                    : JavaVersion.VERSION_21,
		springBootVersion              : '3.3.2',
		springCloudVersion             : '2023.0.3',
		springCloudAlibabaVersion      : '2022.0.0.0-RC2',
		junitVersion                   : '4.13.2',
		lombokVersion                  : '1.18.30',
		nettyVersion                   : '4.1.112.Final',

		// 日志版本管理
		slf4jApiVersion                : '2.0.16',
		logbackVersion                 : '1.5.15',

		// 数据源
		mysqlVersion                   : '8.3.0',
		hibernateVersion               : '6.6.11.Final',
		mybatisVersion                 : '3.0.4',
		mybatisPlusStarterVersion      : '3.5.5',
		dynamicDatasourceStarterVersion: '4.3.1',
		druidStarterVersion            : '1.2.24',
	]

	libraries = [
		junit : "junit:junit:$versions.junitVersion",
		lombok: "org.projectlombok:lombok:$versions.lombokVersion",
		netty : "io.netty:netty-all:$versions.nettyVersion"
	]

	springLibraries = [
		webflux : 'org.springframework.boot:spring-boot-starter-webflux',
		actuator: 'org.springframework.boot:spring-boot-starter-actuator',
	]

	slf4jLibraries = [
		slf4jApi      : "org.slf4j:slf4j-api:$versions.slf4jApiVersion",
		logbackCore   : "ch.qos.logback:logback-core:$versions.logbackVersion",
		logbackClassic: "ch.qos.logback:logback-classic:$versions.logbackVersion",
	]

	jpaLibraries = [
		mysql    : "com.mysql:mysql-connector-j:$versions.mysqlVersion",
		hibernate: "org.hibernate.orm:hibernate-core:$versions.hibernateVersion",
	]

	mybatisPlusLibraries = [
		mysql            : "com.mysql:mysql-connector-j:$versions.mysqlVersion",
		mybatisSpring    : "org.mybatis:mybatis-spring:$versions.mybatisVersion",
		mybatisPlus      : "com.baomidou:mybatis-plus-spring-boot3-starter:$versions.mybatisPlusStarterVersion",
		dynamicDataSource: "com.baomidou:dynamic-datasource-spring-boot3-starter:$versions.dynamicDatasourceStarterVersion",
		druid            : "com.alibaba:druid-spring-boot-3-starter:$versions.druidStarterVersion",
	]

	springMavenBom = [
		springBoot        : "org.springframework.boot:spring-boot-dependencies:$versions.springBootVersion",
		springCloud       : "org.springframework.cloud:spring-cloud-dependencies:$versions.springCloudVersion",
		springCloudAlibaba: "com.alibaba.cloud:spring-cloud-alibaba-dependencies:$versions.springCloudAlibabaVersion",
	]

	gradlePlugins = [
		springDependencyManagement: "io.spring.gradle:dependency-management-plugin:1.0.11.RELEASE"
	]

	mavenRepositories = [
		aliyun      : 'https://maven.aliyun.com/repository/public/',
		gradlePlugin: 'https://plugins.gradle.org/m2/'
	]
}