ext {
	application = [
		name           : 'NettyServer',
		manifestVersion: '1.0',
		mainClass      : '',
	]

	versions = [
		javaVersion                    : JavaVersion.VERSION_21,
		junitVersion                   : '4.13.2',
		lombokVersion                  : '1.18.30',
		nettyVersion                   : '4.1.112.Final',

		// Spring 版本管理
		springBootVersion              : '3.3.2',
		springCloudVersion             : '2023.0.3',
		springCloudAlibabaVersion      : '2022.0.0.0-RC2',
		springAIVersion                : '1.0.0-SNAPSHOT',

		// LangChain4j 版本管理
		langchain4jVersion             : '1.1.0',
		langchain4jSpringBootVersion   : '1.1.0-beta7',

		// Flink 版本管理
		flinkVersion                   : '1.18.0',
		flinkCDCMySQLVersion           : '3.0.0',

		// 日志版本管理
		slf4jApiVersion                : '2.0.16',
		logbackVersion                 : '1.5.15',

		// 数据源
		mysqlVersion                   : '8.3.0',
		hibernateVersion               : '6.6.11.Final',
		mybatisVersion                 : '3.0.4',
		mybatisPlusStarterVersion      : '3.5.5',
		dynamicDatasourceStarterVersion: '4.3.1',
		druidStarterVersion            : '1.2.24',
	]

	libraries = [
		junit : "junit:junit:$versions.junitVersion",
		lombok: "org.projectlombok:lombok:$versions.lombokVersion",
		netty : "io.netty:netty-all:$versions.nettyVersion"
	]

	// SpringBoot 依赖
	springBootLibraries = [
		webflux : 'org.springframework.boot:spring-boot-starter-webflux',
		actuator: 'org.springframework.boot:spring-boot-starter-actuator',
	]

	// SpringAI 依赖
	springAILibraries = [
		springAiBom             : "org.springframework.ai:spring-ai-bom:$versions.springAIVersion",
		springOpenAI            : 'org.springframework.ai:spring-ai-openai',
		springAiMCPServerWebFlux: 'org.springframework.ai:spring-ai-starter-mcp-server-webflux'
	]

	// LangChain4j 依赖
	langchain4jLibraries = [
		langchain4jBom             : "dev.langchain4j:langchain4j-bom:$versions.langchain4jVersion",
		langchain4jOpenAI          : 'dev.langchain4j:langchain4j-open-ai',
		langchain4jMCP             : 'dev.langchain4j:langchain4j-mcp',
		langChain4j                : 'dev.langchain4j:langchain4j',
		langChain4jReactor         : 'dev.langchain4j:langchain4j-reactor',
		langchain4jOpenAISpringBoot: "dev.langchain4j:langchain4j-open-ai-spring-boot-starter:$versions.langchain4jSpringBootVersion",
		langchain4jSpringBoot      : "dev.langchain4j:langchain4j-spring-boot-starter:$versions.langchain4jSpringBootVersion",
	]

	// Flink 依赖
	flinkLibraries = [
		flinkJava         : "org.apache.flink:flink-java:$versions.flinkVersion",
		flinkStreamJava   : "org.apache.flink:flink-streaming-java:$versions.flinkVersion",
		flinkClients      : "org.apache.flink:flink-clients:$versions.flinkVersion",
		flinkTablePlanner : "org.apache.flink:flink-table-planner_2.12:$versions.flinkVersion",
		flinkTableRuntime : "org.apache.flink:flink-table-runtime:$versions.flinkVersion",
		flinkTableAPIJava : "org.apache.flink:flink-table-api-java-bridge:$versions.flinkVersion",
		flinkConnectorBase: "org.apache.flink:flink-connector-base:$versions.flinkVersion",
		flinkCDCMySQL     : "com.ververica:flink-connector-mysql-cdc:$versions.flinkCDCMySQLVersion"
	]

	slf4jLibraries = [
		slf4jApi      : "org.slf4j:slf4j-api:$versions.slf4jApiVersion",
		logbackCore   : "ch.qos.logback:logback-core:$versions.logbackVersion",
		logbackClassic: "ch.qos.logback:logback-classic:$versions.logbackVersion",
	]

	jpaLibraries = [
		mysql    : "com.mysql:mysql-connector-j:$versions.mysqlVersion",
		hibernate: "org.hibernate.orm:hibernate-core:$versions.hibernateVersion",
	]

	mybatisPlusLibraries = [
		mysql            : "com.mysql:mysql-connector-j:$versions.mysqlVersion",
		mybatisSpring    : "org.mybatis:mybatis-spring:$versions.mybatisVersion",
		mybatisPlus      : "com.baomidou:mybatis-plus-spring-boot3-starter:$versions.mybatisPlusStarterVersion",
		dynamicDataSource: "com.baomidou:dynamic-datasource-spring-boot3-starter:$versions.dynamicDatasourceStarterVersion",
		druid            : "com.alibaba:druid-spring-boot-3-starter:$versions.druidStarterVersion",
	]

	springMavenBom = [
		springBoot        : "org.springframework.boot:spring-boot-dependencies:$versions.springBootVersion",
		springCloud       : "org.springframework.cloud:spring-cloud-dependencies:$versions.springCloudVersion",
		springCloudAlibaba: "com.alibaba.cloud:spring-cloud-alibaba-dependencies:$versions.springCloudAlibabaVersion",
	]

	gradlePlugins = [
		springDependencyManagement: "io.spring.gradle:dependency-management-plugin:1.0.11.RELEASE"
	]

	mavenRepositories = [
		aliyun      : 'https://maven.aliyun.com/repository/public/',
		gradlePlugin: 'https://plugins.gradle.org/m2/',
		milestone   : 'https://repo.spring.io/milestone',
		snapshot    : 'https://repo.spring.io/snapshot'
	]
}